#!/usr/bin/env bash
BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(feature|bugfix|hotfix)/PLC-[0-9]+$|^release/[0-9]+\.[0-9]+\.[0-9]+$"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Commit rejected: branch name must match '(feature|bugfix|hotfix)/PLC-NNN' or 'release/X.Y.Z'"
  exit 1
fi

STAGED=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(ts|tsx|md)$')
if [ -n "$STAGED" ]; then
  git stash --keep-index --include-untracked --quiet
  echo "$STAGED" | xargs pnpm exec prettier --write
  echo "$STAGED" | xargs git add
  git stash pop --quiet
fi

pnpm lint && pnpm typecheck
